import '../db/db_helper.dart';
import '../models/contact.dart';
import '../models/interaction.dart';
import '../models/prayer_request.dart';

/// Categorisation of relationship-health insights surfaced on the analytics
/// page. Each value maps to a deterministic signal computed locally.
enum RelationshipInsightType {
  /// A previously well-tended contact has gone unusually quiet relative to
  /// the user's own historical cadence with them.
  driftingContact,

  /// A contact has not been interacted with for an extended absolute period.
  silenceStreak,

  /// Contact has multiple pending prayer requests older than 30 days.
  stalePrayerRequests,

  /// A prayer request was answered recently — a positive signal worth
  /// celebrating.
  answeredPrayer,

  /// Aggregate completion percentage for past follow-up reminders.
  followUpCompletionRate,
}

/// A single relationship-health observation rendered as a card on the
/// analytics dashboard.
///
/// The deterministic [title] is always populated. The optional [phrasing]
/// field is filled in later by an LLM pass when AI features are enabled;
/// callers should render the card with [title] alone if [phrasing] is null.
class RelationshipInsight {
  const RelationshipInsight({
    required this.id,
    required this.type,
    required this.title,
    this.contactId,
    this.contactName,
    this.details,
    this.phrasing,
  });

  /// Stable identifier so the UI can persist dismissals across reloads.
  /// Format: `<type>` for global insights, `<type>:<contactId>` otherwise.
  final String id;

  final RelationshipInsightType type;

  /// Short deterministic copy, e.g. "Drifting: Alice".
  final String title;

  final String? contactId;
  final String? contactName;

  /// Structured numbers backing the insight, used by the LLM phrasing pass
  /// and exposed to the UI for the subtitle line.
  final Map<String, Object?>? details;

  /// Optional natural-language line generated by the on-device LLM.
  final String? phrasing;

  RelationshipInsight copyWith({String? phrasing}) {
    return RelationshipInsight(
      id: id,
      type: type,
      title: title,
      contactId: contactId,
      contactName: contactName,
      details: details,
      phrasing: phrasing ?? this.phrasing,
    );
  }
}

/// Computes deterministic relationship-health insights from local data.
///
/// All work is done in-memory against [Contact.interactions] and
/// [Contact.prayerRequests]; the on-device LLM is not consulted here.
class RelationshipInsightsRepository {
  RelationshipInsightsRepository({DBHelper? dbHelper, DateTime Function()? now})
      : _dbHelper = dbHelper ?? DBHelper(),
        _now = now ?? DateTime.now;

  final DBHelper _dbHelper;
  final DateTime Function() _now;

  /// Long-silence threshold for a contact with at least one prior interaction.
  static const Duration silenceThreshold = Duration(days: 60);

  /// Minimum number of prior interactions required before we'll claim a
  /// contact is "drifting" relative to their typical cadence.
  static const int driftMinInteractions = 4;

  /// Drift multiplier: current gap must exceed this many medians.
  static const double driftMultiplier = 2.0;

  /// Minimum pending prayer-request count to flag as stale.
  static const int stalePrayerMinCount = 3;

  /// Pending prayer requests older than this duration count toward the
  /// stale-prayer-requests insight.
  static const Duration stalePrayerAge = Duration(days: 30);

  /// Recent answered-prayer window for the celebration insight.
  static const Duration answeredPrayerWindow = Duration(days: 7);

  /// Hard cap on per-contact insights returned (drift + silence). Stops a
  /// neglected address book from drowning the page in cards.
  static const int maxPerContactInsights = 5;

  Future<List<RelationshipInsight>> buildInsights() async {
    final contacts = await _dbHelper.getContacts();
    final now = _now();

    final drifting = <RelationshipInsight>[];
    final silent = <RelationshipInsight>[];
    final stalePrayers = <RelationshipInsight>[];
    final answered = <RelationshipInsight>[];

    int totalDueFollowUps = 0;
    int completedFollowUps = 0;

    for (final contact in contacts) {
      final interactions = [...contact.interactions]
        ..sort((a, b) => a.occurredAt.compareTo(b.occurredAt));

      final drift = _detectDrift(contact, interactions, now);
      if (drift != null) drifting.add(drift);

      final silence = _detectSilence(contact, interactions, now);
      if (silence != null) silent.add(silence);

      final stale = _detectStalePrayers(contact, now);
      if (stale != null) stalePrayers.add(stale);

      answered.addAll(_detectAnsweredPrayers(contact, now));

      for (final interaction in interactions) {
        final followUpAt = interaction.followUpAt;
        if (followUpAt == null || !followUpAt.isBefore(now)) continue;
        totalDueFollowUps += 1;
        if (_hasInteractionAfter(interactions, followUpAt)) {
          completedFollowUps += 1;
        }
      }
    }

    // Drifting first (urgent + actionable), then silence streaks, then
    // stale prayers, then the global follow-up rate, then the celebratory
    // answered-prayer cards last so they don't bury the work items.
    drifting.sort((a, b) => _gapDays(b).compareTo(_gapDays(a)));
    silent.sort((a, b) => _gapDays(b).compareTo(_gapDays(a)));

    final perContact = <RelationshipInsight>[
      ...drifting,
      ...silent,
    ].take(maxPerContactInsights).toList();

    final result = <RelationshipInsight>[
      ...perContact,
      ...stalePrayers,
    ];

    final globalFollowUp = _buildFollowUpRate(
      totalDueFollowUps,
      completedFollowUps,
    );
    if (globalFollowUp != null) result.add(globalFollowUp);

    result.addAll(answered);
    return result;
  }

  RelationshipInsight? _detectDrift(
    Contact contact,
    List<Interaction> sorted,
    DateTime now,
  ) {
    if (sorted.length < driftMinInteractions) return null;

    final gapsDays = <int>[];
    for (var i = 1; i < sorted.length; i++) {
      gapsDays.add(
          sorted[i].occurredAt.difference(sorted[i - 1].occurredAt).inDays);
    }
    final medianGap = _median(gapsDays);
    if (medianGap <= 0) return null;

    final last = sorted.last.occurredAt;
    final currentGapDays = now.difference(last).inDays;
    if (currentGapDays < medianGap * driftMultiplier) return null;
    // Don't surface drift for someone we just spoke to; the silence-streak
    // insight handles the long-tail case anyway.
    if (currentGapDays < 14) return null;

    return RelationshipInsight(
      id: 'drift:${contact.id}',
      type: RelationshipInsightType.driftingContact,
      contactId: contact.id,
      contactName: contact.fullName,
      title: 'Drifting: ${contact.fullName}',
      details: {
        'medianGapDays': medianGap,
        'currentGapDays': currentGapDays,
        'interactionCount': sorted.length,
      },
    );
  }

  RelationshipInsight? _detectSilence(
    Contact contact,
    List<Interaction> sorted,
    DateTime now,
  ) {
    if (sorted.isEmpty) return null;
    final last = sorted.last.occurredAt;
    final gap = now.difference(last);
    if (gap < silenceThreshold) return null;
    return RelationshipInsight(
      id: 'silence:${contact.id}',
      type: RelationshipInsightType.silenceStreak,
      contactId: contact.id,
      contactName: contact.fullName,
      title: 'Unusual silence: ${contact.fullName}',
      details: {
        'gapDays': gap.inDays,
        'lastInteractionAt': last.toIso8601String(),
      },
    );
  }

  RelationshipInsight? _detectStalePrayers(Contact contact, DateTime now) {
    final cutoff = now.subtract(stalePrayerAge);
    final stale = contact.prayerRequests
        .where((p) =>
            p.status == PrayerRequestStatus.pending &&
            p.requestedAt.isBefore(cutoff))
        .toList();
    if (stale.length < stalePrayerMinCount) return null;
    return RelationshipInsight(
      id: 'stale-prayers:${contact.id}',
      type: RelationshipInsightType.stalePrayerRequests,
      contactId: contact.id,
      contactName: contact.fullName,
      title: '${stale.length} pending prayer requests for ${contact.fullName}',
      details: {
        'pendingCount': stale.length,
        'oldestDays': now
            .difference(stale
                .map((p) => p.requestedAt)
                .reduce((a, b) => a.isBefore(b) ? a : b))
            .inDays,
      },
    );
  }

  Iterable<RelationshipInsight> _detectAnsweredPrayers(
    Contact contact,
    DateTime now,
  ) {
    final cutoff = now.subtract(answeredPrayerWindow);
    return contact.prayerRequests
        .where((p) =>
            p.status == PrayerRequestStatus.answered &&
            p.answeredAt != null &&
            p.answeredAt!.isAfter(cutoff))
        .map((p) => RelationshipInsight(
              id: 'answered:${contact.id}:${p.syncId}',
              type: RelationshipInsightType.answeredPrayer,
              contactId: contact.id,
              contactName: contact.fullName,
              title: 'Answered prayer for ${contact.fullName}',
              details: {
                'description': p.description,
                'answeredAt': p.answeredAt!.toIso8601String(),
              },
            ));
  }

  RelationshipInsight? _buildFollowUpRate(int total, int completed) {
    // Need a minimum sample to make the rate meaningful.
    if (total < 5) return null;
    final percent = (completed * 100 / total).round();
    return RelationshipInsight(
      id: 'follow-up-rate',
      type: RelationshipInsightType.followUpCompletionRate,
      title: 'Follow-up completion: $percent%',
      details: {
        'totalDue': total,
        'completed': completed,
        'percent': percent,
      },
    );
  }

  bool _hasInteractionAfter(List<Interaction> sorted, DateTime when) {
    return sorted.isNotEmpty && sorted.last.occurredAt.isAfter(when);
  }

  int _median(List<int> values) {
    if (values.isEmpty) return 0;
    final sorted = [...values]..sort();
    final mid = sorted.length ~/ 2;
    if (sorted.length.isOdd) return sorted[mid];
    return ((sorted[mid - 1] + sorted[mid]) / 2).round();
  }

  int _gapDays(RelationshipInsight insight) {
    final details = insight.details;
    if (details == null) return 0;
    final value = details['currentGapDays'] ?? details['gapDays'];
    return value is int ? value : 0;
  }
}
